### ISSUE TITLE
PDF it came without file extension.

### ISSUE THREAD

**Issue by sajozsattila** [sajozsattila/mur2_editor#2]
Comment on[ reddit.com](https://www.reddit.com/r/Markdown/comments/ngeylk/online_markdown_editor_for_mainly_academic_writing/):  

![image](https://user-images.githubusercontent.com/11258722/119098690-fd2f2a80-ba0d-11eb-9a15-e38b57628268.png)

**Comment by sajozsattila** [comment]
At the moment I can not recreate the issue.

Windows 10 Pro 10.183683 + Firefox 88.0.1 (64-bit):

![image](https://user-images.githubusercontent.com/11258722/119098905-47b0a700-ba0e-11eb-9154-3ce6c6c4006c.png)

The download dialog:
![image](https://user-images.githubusercontent.com/11258722/119099131-7c246300-ba0e-11eb-9ffc-3dc2bb2f5e43.png)

The downloaded file:
![image](https://user-images.githubusercontent.com/11258722/119099511-e1785400-ba0e-11eb-8394-6996c7254274.png)

It is looking like working for me.

**Comment by daskultural** [comment]
I made the comment. So I reproduced the issue.

Windows 10 Home + Firefox 88.0.1 (64-bit):
![imagen](https://user-images.githubusercontent.com/74429205/119894014-13575200-bf0a-11eb-8289-a7956d62999d.png)

Downloades file (the file downloads automatically without download dialog):
![imagen](https://user-images.githubusercontent.com/74429205/119894203-4e598580-bf0a-11eb-8d7f-a0657f48a891.png)

The PDF file can still be opened without file extension and:
![imagen](https://user-images.githubusercontent.com/74429205/119894616-d0e24500-bf0a-11eb-98a6-1176e6baf11a.png)

It reads correctly:
![imagen](https://user-images.githubusercontent.com/74429205/119897450-6c28e980-bf0e-11eb-9f9b-667987f90c85.png)

**Comment by sajozsattila** [comment]
Ok, probably I have managed to reproduce the issue. This is regarding certain Firefox settings: 

![Képernyőfotó 2021-05-28 - 20 16 45](https://user-images.githubusercontent.com/11258722/120032230-cbabf580-bff1-11eb-9288-75a6a427aed9.png)

So, in Firefox it is possible to set the download PDF without dialogue. Like on the above screenshot. To get the dialogue set this back to the default value:

![Képernyőfotó 2021-05-28 - 20 22 07](https://user-images.githubusercontent.com/11258722/120032649-6a385680-bff2-11eb-95f7-04a24e4e7a64.png)

Could you please confirm your settings?

**Comment by sajozsattila** [comment]
Ok, probably I have managed to reproduce the issue. This is regarding certain Firefox settings: 

![Képernyőfotó 2021-05-28 - 20 16 45](https://user-images.githubusercontent.com/11258722/120032230-cbabf580-bff1-11eb-9288-75a6a427aed9.png)

So, in Firefox it is possible to set the download PDF without dialogue. Like on the above screenshot. To get the dialogue set this back to the default value:

![Képernyőfotó 2021-05-28 - 20 22 07](https://user-images.githubusercontent.com/11258722/120032649-6a385680-bff2-11eb-95f7-04a24e4e7a64.png)

Could you please confirm your settings?

**Comment by sajozsattila** [comment]
The issue is the same as in this [problem](https://stackoverflow.com/questions/41947735/custom-name-for-blob-url).

As all modern browser supporting PDF, the expected behaviour of the PDF generation to open in a new tap, with `windows.open()` JavaScript function.  However, this is basically open up a blob, which filenames can not set.  When somebody set the browser to automatic download for pdf files,  like above, basically we save the blob without filename. 


One solution could be to change the default behaviour and instead of open the PDF in a new tab, download straight. But I believe for most user the tab is more convenient, as they straight can see the result, without searching and opening in a different application.  So I rather do not change this behaviour.

**Comment by daskultural** [comment]
I changed the browser settings (I don't remeber when and how I changed said option in first place). Now exporting the PDF file works as intended. Thanks for the time!
